/** Declaration file generated by dts-gen */

export function mkdir(root: any, mode: any, callback: any): any;

export function mkdirSync(root: string, mode?: any): any;

export function rmdir(root: any, callback: any): any;

export function rmdirSync(root: any): any;

export namespace mkdir {
    const prototype: {
    };

}

export namespace mkdirSync {
    const prototype: {
    };

}

export namespace rmdir {
    const prototype: {
    };

}

export namespace rmdirSync {
    const prototype: {
    };

}

