/** Declaration file generated by dts-gen */

declare module 'crc-32' {
export const version: string;

export function bstr(bstr: any, seed: any): any;

export function buf(buf: any, seed: any): any;

export function str(str: any, seed?: any): any;

export namespace bstr {
    const prototype: {
    };

}

export namespace buf {
    const prototype: {
    };

}

export namespace str {
    const prototype: {
    };

}

export namespace table {
    const BYTES_PER_ELEMENT: number;

    const byteLength: number;

    const byteOffset: number;

    const length: number;

    function copyWithin(p0: any, p1: any): any;

    function entries(): any;

    function every(p0: any): any;

    function fill(p0: any): any;

    function filter(p0: any): any;

    function find(p0: any): any;

    function findIndex(p0: any): any;

    function forEach(p0: any): any;

    function includes(p0: any): any;

    function indexOf(p0: any): any;

    function join(p0: any): any;

    function keys(): any;

    function lastIndexOf(p0: any): any;

    function map(p0: any): any;

    function reduce(p0: any): any;

    function reduceRight(p0: any): any;

    function reverse(): any;

    function set(p0: any): any;

    function slice(p0: any, p1: any): any;

    function some(p0: any): any;

    function sort(p0: any): any;

    function subarray(p0: any, p1: any): any;

    function toLocaleString(): any;

    function toString(): any;

    function values(): any;

    namespace buffer {
        const byteLength: number;

        function slice(p0: any, p1: any): any;

    }

}
}
