version: 2
jobs:
  build:
    docker:
      - image: circleci/node:carbon-stretch-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - ts-dependencies-{{ checksum "package.json" }}
            - ts-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn

          key: ts-dependencies-{{ checksum "package.json" }}
      - run: yarn run build-prod
      - persist_to_workspace:
          root: workspace
          paths:
            - packages/client/dist/
      - store_artifacts:
          path: packages/client/dist/
          prefix: client
  deploy:
    docker:
      - image: google/cloud-sdk
    attach_workspace:
      at: /tmp/client
    steps:
      - run: |
          echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
          sudo gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
          sudo gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          sudo gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          bin/deploy-static-ci.sh
workflows:
  version: 2
  build:
    jobs: build
  build-deploy:
    jobs:
      - build
      - deploy-job:
          requires:
            - build
          filters:
            branches:
              only: master
