/** Declaration file generated by dts-gen */

export function fromMs(ms: any, format: any): any;

export function fromS(s: any, format: any): any;

export function toMs(time: any, format?: any): any;

export function toS(time: any, format?: any): any;

export namespace fromMs {
    const prototype: {
    };

}

export namespace fromS {
    const prototype: {
    };

}

export namespace toMs {
    const prototype: {
    };

}

export namespace toS {
    const prototype: {
    };

}

