/** Declaration file generated by dts-gen */

export function parse(...args: any[]): void;

export function parseFile(...args: any[]): void;

export function parseFileSync(...args: any[]): void;

export function parseSync(...args: any[]): void;

export function stringify(...args: any[]): void;

export function stringifySync(...args: any[]): void;

