/** Declaration file generated by dts-gen */

export = express_healthcheck;

declare function express_healthcheck(options?: any): any;

declare namespace express_healthcheck {
    const prototype: {};
}
