/** Declaration file generated by dts-gen */

export function branch(dir?: any): any;

export function short(dir?: any): any;

export function count(): any;

export function date(): any;

export function isDirty(): any;

export function isTagDirty(): any;

export function log(): void;

export function message(): any;

export function remoteUrl(): any;

export function tag(markDirty: any): any;

export function tagFirstParent(markDirty: any): any;

export namespace branch {
    const prototype: {
    };

}

export namespace count {
    const prototype: {
    };

}

export namespace date {
    const prototype: {
    };

}

export namespace isDirty {
    const prototype: {
    };

}

export namespace isTagDirty {
    const prototype: {
    };

}

export namespace log {
    const prototype: {
    };

}

export namespace message {
    const prototype: {
    };

}

export namespace remoteUrl {
    const prototype: {
    };

}

export namespace tag {
    const prototype: {
    };

}

export namespace tagFirstParent {
    const prototype: {
    };

}

