/** Declaration file generated by dts-gen */

export function fromMs(ms: any, format: any): any;

export function fromS(s: any, format: any): any;

export function toMs(time: any, format?: any): any;

export function toS(time: any, format?: any): any;

export namespace fromMs {

}

export namespace fromS {

}

export namespace toMs {

}

export namespace toS {

}

